"""empty message

Revision ID: 8370c4827096
Revises:
Create Date: 2025-05-07 22:43:42.440979

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8370c4827096"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_report",
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("report_name", sa.Text(), nullable=False),
        sa.Column("creator_id", sa.UUID(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("device_type", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("report_id"),
    )
    op.create_table(
        "report_media",
        sa.Column("media_id", sa.UUID(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["report_id"], ["device_report.report_id"]),
        sa.PrimaryKeyConstraint("media_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("report_media")
    op.drop_table("device_report")
    # ### end Alembic commands ###
